objective:
  - Ridge Regression[fit_intercept=False,lmbd=[0.1, 0.01]]

dataset: # dataset to run benchmark on
  - simulated

solver: # list of example solvers to do benchmark
  - sklearn
  - glmnet
  - snapml

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
