objective:
  - Lasso Regression[fit_intercept=False,reg=[0.1, 0.01]]

dataset: # dataset to run benchmark on
  - libsvm[rcv1.binary]

solver: # list of example solvers to do benchmark
  - snapml

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
